name: Build Geo-Assets

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Explicitly grant write access for releases
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Builder
        run: |
          go mod tidy
          go run .

      - name: Update Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Geodata Build"
          files: |
            output/*.db
            output/*.dat
            output/*.srs